MVP Tutorial Page
pedrouzcategui/todopractice pull request #20
Opened 2024-03-06 03:35 UTC by pedrouzcategui

2024-03-07 18:38 UTC, AlfredoPrograma requested changes
Generally speaking, nice code and fast implementation :clap:. Take your time to read and apply the suggestions in order to improve the code!

2024-03-07 18:38 UTC, AlfredoPrograma commented on src/app/tutorial/page.tsx
> +                    <button className="mb-6 text-sm text-gray-400 hover:text-gray-800 transition-colors" onClick={() => setStep(-1)}>Go Back</button>
Is there any reason why you used a native button tag? If not, replace it with the `<Button />` component provided by the shadcn library.

2024-03-07 18:38 UTC, AlfredoPrograma commented on src/app/tutorial/page.tsx
> +                            {workspace.name ? workspace.name : "Ex: Wayne Industries"}
You can use the [nullish coalesing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) in order to improve these kind of ternary operations where you want to check if the current value exists and use it or otherwise use a default one.

Basically, the nullish coalesing operator will try to use the given value; if it is `undefined`, then the right hand value will be used.

Here is the code difference applied for this case:

`{ workspace.name ? workspace.name : "Ex: Wayne Industries" }` -> `{ workspace.name ?? "Ex: Wayne Industries }`

It looks as a knit picky change but it is a nice improvement for avoid repetition; specifically on larger accessing properties cases.

2024-03-07 18:38 UTC, AlfredoPrograma commented on src/stores/tutorial.store.ts
> +  setStep: (by) => set((state) => ({ currentStep: state.currentStep + by })),
In my opinion, I would create two step handler functions: `goNext` and `goBack`. I think it is cleaner because:
1. For the current tutorial implementation, user always is going to move forward/backward by **one** step; so it is a little bit redundant indicating the amount of steps (always one xd) state should be updated by.
2. Exposing two declarative functions improves code readability; because just reading its names we know what they do in the context of the tutorial state.

2024-03-07 18:38 UTC, AlfredoPrograma commented on src/types/workspace.interface.ts
> +export interface IWorkspace {
I think you can rebase this branch with `main` branch and use directly **Prisma** provided types. 

As ORM, **Prisma** takes the current database schema and generates types based on it. We should try to use generated types as much as possible in order to avoid types duplication and naming issues.

2024-03-07 18:39 UTC, AlfredoPrograma commented on src/types/workspace.interface.ts
> +export interface IWorkspace {
Also, in I like to declare new types with `type` keyword instead `interface`.

`type` declaration gives you more flexibility when you want to compose complex types. `interfaces` are more rigid and difficult the type composition.

2024-03-07 19:24 UTC, juanzenn commented on src/types/workspace.interface.ts
> +export interface IWorkspace {
I second the use of **type** instead of **interface** as a standard in the codebase.

2024-03-08 04:31 UTC, pedrouzcategui commented on src/app/tutorial/page.tsx
> +                    <button className="mb-6 text-sm text-gray-400 hover:text-gray-800 transition-colors" onClick={() => setStep(-1)}>Go Back</button>
I did replace this with the `<Button/>` from shadcn. Thank you for the suggestion.

2024-03-08 04:32 UTC, pedrouzcategui commented on src/app/tutorial/page.tsx
> +                            {workspace.name ? workspace.name : "Ex: Wayne Industries"}
At the end, since the default values of workspace properties are all empty strings, the use of the nullish coalesing operator is not valid. Instead, I used the OR logical operator.

2024-03-08 04:32 UTC, pedrouzcategui commented on src/stores/tutorial.store.ts
> +  setStep: (by) => set((state) => ({ currentStep: state.currentStep + by })),
This was implemented as well.

2024-03-08 04:34 UTC, pedrouzcategui commented on src/types/workspace.interface.ts
> +export interface IWorkspace {
This was also implemented.

2024-03-08 04:35 UTC, AlfredoPrograma commented
FIX

2024-03-08 12:29 UTC, juanzenn commented
Hey @pedrouzcategui, fantastic PR. I just merged it. We'll improve it further down the road.

2024-03-08 12:29 UTC, merged