Feature(profile): implement profile page
pedrouzcategui/todopractice pull request #60
Opened 2024-03-14 12:47 UTC by AlfredoPrograma

- Implement API endpoint for perform profile updating
- Create `dashboard/profile` page for rendering update profile form and profile overview
- Create `UpdateProfileForm` component to allow user to update its name and image
- Some refactors for improving code readability and reusability:
    - Create `constants` directory with `common.ts` and `auth.ts` files for exposing reusable constant data related to specific modules throughout the application.
    - Create `useUploadImage` custom hook for extract file handling and image uploading logic.

2024-03-14 13:49 UTC, juanzenn requested changes

2024-03-14 13:49 UTC, juanzenn commented on .eslintrc.json
> +    "@next/next/no-img-element": "off"
Please, remove this config and use the Image component from Next. I configured the domain already (uploadthing). Plus  I remove the "no optimize" option.

2024-03-14 13:49 UTC, juanzenn commented on src/app/(private)/dashboard/profile/page.tsx
> +  const { user } = (await getSession()) as Session;
Hard casting values like this **could** give problems down the role. Easier to make an if check for the user.

2024-03-14 13:49 UTC, juanzenn commented on src/components/dashboard/profile/auth-providers-list.tsx
> +            provider as AuthProvider,
So this is why you cast the AuthProvider. Wouldn't be easier to make `userLinkedProviders` an array of keys (think ['discord', 'google']) and then compare like `provider === key`?

That is just my thought since the providers from the database **aren't** AuthProvider, and casting them feels wrong.

2024-03-14 13:49 UTC, juanzenn commented on src/components/dashboard/profile/auth-providers-list.tsx
> +              <Button
For now, this is OKAY. Keep in mind that here users can link their profile to another provider.

2024-03-14 13:49 UTC, juanzenn commented on src/hooks/profile.ts
> +      const response = await api.put<Prisma.UserUpdateInput>("/profile", data);
Does the response is the same type as the data? This may be a mistake. Shouldn't return a User or Profile?

2024-03-14 13:49 UTC, juanzenn commented on src/hooks/uploadImage.ts
> +export function useUploadImage() {
Love it. I have to implement this on the workspace CRUD. Thank you 😄

2024-03-15 02:21 UTC, AlfredoPrograma commented on src/components/dashboard/profile/auth-providers-list.tsx
> +            provider as AuthProvider,
Sure. I will make the change. However we cannot avoid casting `provider` value to `AuthProvider` for accessing to provider metadata in `AUTH_PROVIDERS` object; because that object is hard typed as `Record<AuthProvider, AuthProviderMetadata>`.

2024-03-15 02:28 UTC, AlfredoPrograma commented on .eslintrc.json
> +    "@next/next/no-img-element": "off"
Sorry, I removed it arbitrarily because I am dictator :sunglasses:

2024-03-15 02:44 UTC, AlfredoPrograma commented on src/app/(private)/dashboard/profile/page.tsx
> +  const { user } = (await getSession()) as Session;
Done. However it is redundant checking user existence for each protected page since parent components (like private `layout.tsx`) are already checking this condition.

Maybe we can abstract this check passing session as prop to children pages from `layout` component? Idk :thinking:

2024-03-15 02:44 UTC, AlfredoPrograma commented on src/app/(private)/dashboard/profile/page.tsx
> +  const { user } = (await getSession()) as Session;
For sure it is non-priority optimization, so for now we can keep checking user existence on each page.

2024-03-15 02:46 UTC, AlfredoPrograma commented on src/hooks/profile.ts
> +      const response = await api.put<Prisma.UserUpdateInput>("/profile", data);
Sure, I was wrong. Actually endpoint does not return a response :laughing: Endpoint returns empty object because we dont need the updated data on the response body.

2024-03-15 11:52 UTC, juanzenn commented on src/components/dashboard/profile/auth-providers-list.tsx
> +            provider as AuthProvider,
Couldn't we check for only a prop (say provider.name) rather than the whole object?

2024-03-15 11:55 UTC, juanzenn commented on src/app/(private)/dashboard/profile/page.tsx
> +  const { user } = (await getSession()) as Session;
Hmmm. So, are we casting because, in this instance, we know better than TypeScript? I think it makes sense. There has to be a way to **not cast** and have the Session as not null in authenticated routes...

2024-03-15 11:56 UTC, juanzenn commented on src/hooks/profile.ts
> +      const response = await api.put<Prisma.UserUpdateInput>("/profile", data);
I highly advise returning at least an object { "ok": true } if nothing more of value is needed. Other than that, that's cool

2024-03-15 11:57 UTC, juanzenn commented
I'm merging the PR since it's all good. Just a few conversations left; mostly for education purposes.

2024-03-15 11:57 UTC, juanzenn approved these changes

2024-03-15 11:57 UTC, merged

2024-03-15 21:35 UTC, AlfredoPrograma commented on src/app/(private)/dashboard/profile/page.tsx
> +  const { user } = (await getSession()) as Session;
Sure. We are casting because we are **sure**  that `session` and `user` variables are available. We know that because this page is rendered by the **private layout**; which already verifies user existence.

2024-03-15 21:35 UTC, AlfredoPrograma commented on src/app/(private)/dashboard/profile/page.tsx
> +  const { user } = (await getSession()) as Session;
We should research in order to make it cleaner in a future.

2024-03-15 21:41 UTC, AlfredoPrograma commented on src/hooks/profile.ts
> +      const response = await api.put<Prisma.UserUpdateInput>("/profile", data);
Hmmm. idk how passing `ok: true` improves the response. I mean, if there is not content for the response; we can return empty object directly.

In fact there is an http code which tags the response as `no-content`. [Reference](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204)

I mean, I think we can use `ok: true` but only if we turn it into a standard for all api responses; in order to make the code consistent.

2024-03-15 21:44 UTC, AlfredoPrograma commented on src/components/dashboard/profile/auth-providers-list.tsx
> +            provider as AuthProvider,
I'm not sure. Actually I'm kinda confuse now. We can take a look in a live coding session to improve the code logic and clarify given suggestions :+1: